version: '3.8'
services:
  s2orc-doc2json:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=doc2json/flask/app.py
    networks:
      - grobid-network
    extra_hosts:
      - "localhost:host-gateway"

networks:
  grobid-network:
    external: true