version: '3.8'

services:
  grobid:
    image: lfoppiano/grobid:0.8.1
    ports:
      - "8070:8070"
    init: true
    ulimits:
      core: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  s2orc-doc2json:
    build:
      context: ./s2orc-doc2json
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=doc2json/flask/app.py
    depends_on:
      grobid:
        condition: service_healthy